### ISSUE TITLE
git repository is incorrect

### ISSUE THREAD

**Issue by karenetheridge** [hostgator/Business-CyberSource#6]
The metadata is pointing to https://github.com/xenoterracide/Business-CyberSource as the canonical repository, whereas it seems that now the hostgator user is releasing this distribution. please fix!

(Also please do not exclude the dist.ini file from the release; it makes it more difficult to figure out how a distribution is built and trace it back to its source.)

**Comment by elderling** [comment]
We fixed the metadata but didn't fix the `dist.ini` so I created another issue so that part doesn't get forgotten.
